### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by claudiorrrr** [creativecommons/wp-theme-openglam#12]
![image](https://dsh.re/ea10b)

Change it to the new logo ;)

**Comment by claudiorrrr** [comment]
fixed by scann

**Comment by fcoveram** [comment]
Currently, some browsers allow the dark mode and the new favicon has a background color that modifies the natural shape of the logo. Here is an example.

<img width="61" alt="Screen Shot 2020-09-29 at 12 44 58" src="https://user-images.githubusercontent.com/895819/94581538-99bf7500-0251-11eb-954b-39d15f8a5e11.png">

I recommend using the orange color for the icon without background. I will look good over dark and white background. 

I can create/update the favicon if we all agree on this
