### ISSUE TITLE
Find image source and correct attribution

### ISSUE THREAD

**Issue by claudiorrrr** [creativecommons/wp-theme-openglam#14]
![image](https://user-images.githubusercontent.com/390030/94487393-4dbff200-01b7-11eb-9883-24dc3e39ff4e.png)

maybe @panchovm?

**Comment by fcoveram** [comment]
Yes. That's the image attribution zone. It's a content change that doesn't need a code update.

**Comment by hugosolar** [comment]
It can be changed in `Appearance > Customize` and then `OpenGlam Settings > Header Image`

**Comment by hugosolar** [comment]
As I can see the image has a link to the attribution, I correct the title according to the source "Station Thirty-Eight: Fujikawa, Scene at the Border, from the Fifty-Three Stations of the Tokaido"

**Comment by cammyb181** [comment]
> hello_world=hammer_down_dev.md

- [ ]
