### ISSUE TITLE
Alignment of elements in main nav

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/wp-theme-openglam#2]
**Page: Home
Resolution: Full HD**

## Expectation
The list of links in the main nav (left sidebar) should be left-aligned with the logo.

## Screenshots
<img width="248" alt="Screen Shot 2020-09-28 at 16 56 14" src="https://user-images.githubusercontent.com/895819/94479718-97a2db00-01ab-11eb-968a-668938b48c18.png">

**Comment by hugosolar** [comment]
Fixed
