### ISSUE TITLE
More value in the font-weight style of all headings

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/wp-theme-openglam#3]
**General implementation**

## Description
I am comparing the mockups with the site and it seems that the value `700` for `font-weight` matches better with the design. Therefore, all heading might have that value. 

## Additional context
It tends to happen that font-rendering in design software is slightly different than font-rendering in browsers. And endless discussion that requires eagle eyes 👀.

### Home page example
<img width="750" alt="Screen Shot 2020-09-28 at 17 06 30" src="https://user-images.githubusercontent.com/895819/94480636-f9b01000-01ac-11eb-8d46-999d44d7231f.png">

**Comment by hugosolar** [comment]
Fixed
