### ISSUE TITLE
Eliminate the margin-bottom of card

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/wp-theme-openglam#30]
## Description
Page: Why
Resolution: Full HD

## Alternatives
I noticed that each card has a margin-bottom value that increases the space between card rows. If we delete it, space will be `28px` as it was developed.

## Screenshot
<img width="652" alt="Screen Shot 2020-09-29 at 12 35 54" src="https://user-images.githubusercontent.com/895819/94580454-557fa500-0250-11eb-9ffa-0d6b12861d9e.png">

**Comment by hugosolar** [comment]
I changed it just for touch devices since in that breakpoint we use just once column
