### ISSUE TITLE
Hover style of default links

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/wp-theme-openglam#4]
## Expectation
The hover style of default links should have an `underline` style instead of a color change.

### Current implementation
<img width="653" alt="Screen Shot 2020-09-28 at 17 07 29" src="https://user-images.githubusercontent.com/895819/94480897-54496c00-01ad-11eb-82c3-a9cd1b438fb2.png">

### Desired implementation
<img width="669" alt="Screen Shot 2020-09-28 at 17 09 26" src="https://user-images.githubusercontent.com/895819/94480956-67f4d280-01ad-11eb-879a-67f854694f38.png">

**Comment by hugosolar** [comment]
Fixed
just for links inside the `.content` element which applies for content generated by Gutenberg
