### ISSUE TITLE
Font-weight value of a link in footer

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/wp-theme-openglam#5]
**General implementation**

## Expectation
The `Slack community` button in footer should have a value of `700` for `font-weight`

### Current implementation
<img width="368" alt="Screen Shot 2020-09-28 at 17 13 01" src="https://user-images.githubusercontent.com/895819/94481294-e2255700-01ad-11eb-9217-2e73a0a6ee9a.png">

**Comment by hugosolar** [comment]
there's this other opened issue #16 by @claudioruiz
what should we do here?

**Comment by fcoveram** [comment]
Lets him decide

**Comment by claudiorrrr** [comment]
Logo and not letters plz
