### ISSUE TITLE
Size of the main image in home page

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/wp-theme-openglam#6]
**Page: Home
Resolution: Full HD**

## Expectation
The image's height must be `170px` or a similar value. Not it is `220px` and looks to big compared to all remained content.

### Current implementation
<img width="1440" alt="Screen Shot 2020-09-28 at 17 43 58" src="https://user-images.githubusercontent.com/895819/94484222-74c7f500-01b2-11eb-8378-56a9a54e26e4.png">

**Comment by hugosolar** [comment]
Fixed
