### ISSUE TITLE
Increase the space between paragraph and links

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/wp-theme-openglam#8]
**Page: Home
Resolution: Full HD**

## Expectation
Increase the space between the paragraph (below the main title) and links to internal pages.

### Current implementation
<img width="1074" alt="Screen Shot 2020-09-28 at 17 49 52" src="https://user-images.githubusercontent.com/895819/94484641-21a27200-01b3-11eb-9606-de2610de49b3.png">

**Comment by hugosolar** [comment]
Increased to `1.6rem` (30px app)
