### ISSUE TITLE
Increase the size of the logo on the sidebar

### ISSUE THREAD

**Issue by claudiorrrr** [creativecommons/wp-theme-openglam#9]
![image](https://user-images.githubusercontent.com/390030/94486298-97a7d880-01b5-11eb-9a9e-7df06a09130b.png)

This is maybe for @panchovm to review, but the size should be more equivalent to H1 than what it is currently

**Comment by fcoveram** [comment]
Yes. The logo's `width` should be `110px`. We should use that size and the proportional size for `height`.
